### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by DakariMona** [Keksuccino/Load-My-Resources#11]
**1.20.6 support**
for right now I can't run the game with this mod without this error

java.lang.NoSuchMethodError: 'net.minecraft.class_3288 net.minecraft.class_3288.method_14456(java.lang.String, net.minecraft.class_2561, boolean, net.minecraft.class_3288$class_7680, net.minecraft.class_3288$class_7679, net.minecraft.class_3288$class_3289, boolean, net.minecraft.class_5352)'
	at de.keksuccino.loadmyresources.pack.PackHandler.createPack(PackHandler.java:44)
	at de.keksuccino.loadmyresources.pack.LMRRepositorySource.method_14453(LMRRepositorySource.java:16)
	at net.minecraft.class_3283.method_29212(class_3283.java:43)
	at net.minecraft.class_3283.method_14445(class_3283.java:36)
	at net.minecraft.class_310.<init>(class_310.java:539)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
please fix it i want to use it

**Comment by Keksuccino** [comment]
There will be no more updates for LMR. I recommend you to use other resource loader mods. They probably work way better than LMR anyways.
